name = "nabeatsu"
type = "javascript"

account_id = ""
workers_dev = true
# route = ""
# zone_id = ""
routes = ["api.kabomk.com/nebeatsu*"]

compatibility_date = "2022-04-27"
compatibility_flags = []

# [durable_objects]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
durable_objects_persist = false
